### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by FanghanHu** [benfah/Bags#1]
I saw you on your spigot post, and you said this plugin does not effect other item's textures.
yet I saw in the BagManager class you are using sword item with damage values for the base item, wouldn't that cause the vanilla sword to temporarily change texture when reaching your set damage value?

did you find a work around for this?

**Comment by benfah** [comment]
No, it wouldn't., because I set the damage value to 0.5 (standard item), and set it to unbreakable. The resourcepack can look for items with a damage value and the unbreakable tag. If this is matching, the model will get redirected.

**Comment by FanghanHu** [comment]
thanks, got it working.

On Fri, May 6, 2016 at 4:06 AM -0700, "benfah" <notifications@github.com<mailto:notifications@github.com>> wrote:

No, it wouldn't., because I set the damage value to 0.5 (standard item), and set it to unbreakable. The resourcepack can look for items with a damage value and the unbreakable tag. If this is matching, the model will get redirected.

##

**Comment by FanghanHu** [comment]
Hey man, I made a resource pack API which can automatically merge custom resource from multiple plugins: https://www.spigotmc.org/threads/a-resource-pack-api.146846/#post-1577094
check it out.

**Comment by benfah** [comment]
No Way! I've done something similar. Your plugin is clearly better than mine. I'll use it for Bags ^^.

**Comment by FanghanHu** [comment]
nice, let me know if you need help.

**Comment by benfah** [comment]
One question. Can you make the damage value static?

**Comment by FanghanHu** [comment]
no, the manager will assign damage values on the run. if you need to produce the item, you can get the damage value from the Custom item class, or use its createItemstack() method.

**Comment by benfah** [comment]
Hi, I've got a small question.
`NBTCompoundWrapper nbt = NBTUtils.getNBTTag(stack);
nbt.setInt("bagid", id);
NBTUtils.setNBTTag(stack, nbt);`
What is wrong at this code?

**Comment by FanghanHu** [comment]
minecraft does not allow custom nbt tags, they remove everything that they don't recognize.
at least last time i tried, it did't allow me to add anything beside existing tags like: Unbreakable tags.

nvm about the getInstance() nonsense, I forgot what I did in NBTUtils. sorry.
