### ISSUE TITLE
IOException if plugin data directory is missing

### ISSUE THREAD

**Issue by seeker** [benfah/Bags#4]
If the server is started with a missing `plugins/Bags/` directory, an exception is thrown.

**How to reproduce**
1. Make sure the plugin directory does not contain a `Bags` directory
2. Start the server

**Actual results**
The plugin throws an exception and creates the directory and files.

**Expected results**
The plugin creates the directory (and logs the action), then creates the files.

**Additional information**
OS: Ubuntu 15.10 64-Bit
Java: openjdk version 1.8.0_91 64-Bit
Plugin: 1.3.5
Spigot: 1.9.4

[stacktrace.txt](https://github.com/benfah/Bags/files/310586/stacktrace.txt)

**Comment by benfah** [comment]
Thank you! Fixed :D.
