### ISSUE TITLE
Could not pass event PlayerJoinEvent to Bags v2.0.0 / Spigot 1.12

### ISSUE THREAD

**Issue by njdro** [benfah/Bags#5]
`[ ERROR]: Could not pass event PlayerJoinEvent to Bags v2.0.0`
https://pastebin.com/vGhBqp2B

`[Server thread/INFO]: This server is running CraftBukkit version git-Spigot-596221b-b1b9ab0 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
`

**Comment by FanghanHu** [comment]
Looks like you got server version 1.12, but thos plugin is for 1.11
